# Generated by Django 2.2.16 on 2020-10-31 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misCar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='carw',
            fields=[
                ('nombre', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('precio', models.IntegerField()),
                ('descripcion', models.CharField(max_length=200)),
                ('stock', models.IntegerField()),
            ],
        ),
    ]
