# Generated by Django 2.2.16 on 2020-11-01 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misCar', '0002_carw'),
    ]

    operations = [
        migrations.AddField(
            model_name='carw',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imgInsumosCar'),
        ),
    ]
