# Generated by Django 3.1.2 on 2020-11-01 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misCar', '0004_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='mision',
            fields=[
                ('nombre', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='vicion',
            fields=[
                ('nombre', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=400)),
            ],
        ),
    ]
